baseURL = 'http://localhost:3000/'
languageCode = 'en-US'
title = 'Blog.'
theme = 'tailwind'
defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = true

[params]
  description = 'A minimal tech blog.'

[languages]
  [languages.en]
    languageName = 'English'
    weight = 1
    title = 'Blog.'
    contentDir = 'content/en'
    [languages.en.params]
      description = 'Thoughts, notes and little experiments.'
  [languages.ru]
    languageName = 'Русский'
    weight = 2
    title = 'Блог.'
    contentDir = 'content/ru'
    [languages.ru.params]
      description = 'Мысли, заметки и небольшие эксперименты.'

[languages.en.menus]
  [[languages.en.menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10
  [[languages.en.menus.main]]
    name = 'Tags'
      pageRef = '/tags'
      weight = 20
[languages.ru.menus]
  [[languages.ru.menus.main]]
    name = 'Главная'
    pageRef = '/'
    weight = 10
  [[languages.ru.menus.main]]
    name = 'Теги'
      pageRef = '/tags'
      weight = 20
[menus]
  # EN
  # RU


[build]
  [build.buildStats]
    enable = true
  [[build.cachebusters]]
    source = 'assets/notwatching/hugo_stats\.json'
    target = 'css'
  [[build.cachebusters]]
    source = '(postcss|tailwind)\.config\.js'
    target = 'css'
[module]
  [[module.mounts]]
    source = 'assets'
    target = 'assets'
  [[module.mounts]]
    disableWatch = true
    source = 'hugo_stats.json'
    target = 'assets/notwatching/hugo_stats.json'